set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_INSTALL OFF CACHE BOOL "" FORCE)
FetchContent_Declare(glfw URL https://github.com/glfw/glfw/archive/7b6aead9fb88b3623e3b3725ebb42670cbe4c579.tar.gz URL_HASH SHA256=169d49096e339caabbc12e1762273c5cb9130a535a282ba46cf5c14ab6e55694 DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(glm URL https://github.com/g-truc/glm/archive/0af55ccecd98d4e5a8d1fad7de25ba429d60e863.tar.gz URL_HASH SHA256=e7f187d83523f505eb38dd25d297ea6c0d4ed856d733e808f18253f5a8fa88a0 DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(glad URL https://github.com/Dav1dde/glad/archive/73db193f853e2ee079bf3ca8a64aa2eaf6459043.tar.gz URL_HASH SHA256=33dbeae44d8315ece57e14eba4b1b4a02ac5406d1c4f49cd20048c91522a6b9a DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR cmake)
FetchContent_Declare(imgui URL https://github.com/ocornut/imgui/archive/52fe0a05a7b1aa180a202bb24f0f2a049a9c1b7d.tar.gz URL_HASH SHA256=84196b24c66cd3be22cb0b313ef70941481238ec33e595401b07976baeb7c3db DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(qrcode URL https://github.com/nayuki/QR-Code-generator/archive/7ad95cedd8464a87f82221283612732ae4f3f305.tar.gz URL_HASH SHA256=4cc496832f58c531c1a322b92350559e9f64207116cfd3db541334fe86049735 DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(nvcodec URL https://github.com/FFmpeg/nv-codec-headers/archive/57f8cc0bb68e5f16f3787ea92cea59000f7bf97f.tar.gz URL_HASH SHA256=bafc79a8183093dfcf7bf2ce316ef9eeb9f460199ebffdf4201ec249db87e6ab DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_MakeAvailable(glfw glm glad imgui qrcode nvcodec)
glad_add_library(glad_gl_core_45 STATIC REPRODUCIBLE API gl:core=4.5)
add_library(imgui STATIC "${imgui_SOURCE_DIR}/imgui.cpp" "${imgui_SOURCE_DIR}/imgui_draw.cpp" "${imgui_SOURCE_DIR}/imgui_widgets.cpp" "${imgui_SOURCE_DIR}/imgui_tables.cpp" "${imgui_SOURCE_DIR}/backends/imgui_impl_glfw.cpp" "${imgui_SOURCE_DIR}/backends/imgui_impl_opengl3.cpp")
target_include_directories(imgui PUBLIC "${imgui_SOURCE_DIR}" "${imgui_SOURCE_DIR}/backends")
target_link_libraries(imgui PUBLIC glfw)
add_library(qrcodegen STATIC "${qrcode_SOURCE_DIR}/cpp/qrcodegen.cpp")
target_include_directories(qrcodegen PUBLIC "${qrcode_SOURCE_DIR}/cpp")
set(BUILD_CURL_EXE OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(BUILD_LIBCURL_DOCS OFF CACHE BOOL "" FORCE)
set(BUILD_MISC_DOCS OFF CACHE BOOL "" FORCE)
set(ENABLE_CURL_MANUAL OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBPSL OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBSSH2 OFF CACHE BOOL "" FORCE)
set(CURL_DISABLE_LDAP ON CACHE BOOL "" FORCE)
set(CURL_DISABLE_LDAPS ON CACHE BOOL "" FORCE)
set(CURL_ZLIB OFF CACHE BOOL "" FORCE)
set(CURL_BROTLI OFF CACHE BOOL "" FORCE)
set(CURL_ZSTD OFF CACHE BOOL "" FORCE)
set(USE_NGHTTP2 OFF CACHE BOOL "" FORCE)
set(USE_LIBIDN2 OFF CACHE BOOL "" FORCE)
set(HTTP_ONLY ON CACHE BOOL "" FORCE)
# curl's generated configuration also reads this unprefixed libdatachannel option.
set(USE_MBEDTLS OFF CACHE BOOL "" FORCE)
set(CURL_USE_MBEDTLS OFF CACHE BOOL "" FORCE)
if(WIN32)
  set(CURL_USE_SCHANNEL ON CACHE BOOL "" FORCE)
  set(CURL_USE_OPENSSL OFF CACHE BOOL "" FORCE)
endif()
FetchContent_Declare(curl URL https://github.com/curl/curl/archive/57495c64871d18905a0941db9196ef90bafe9a29.tar.gz URL_HASH SHA256=0c7df3d2730de54d3e8eaa557c04ba60c5b68dab7a3904afd45b8de2bb72dc47 DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_MakeAvailable(curl)
set(USE_MBEDTLS ON CACHE BOOL "" FORCE)
set(USE_NICE OFF CACHE BOOL "" FORCE)
set(NO_EXAMPLES ON CACHE BOOL "" FORCE)
set(NO_TESTS ON CACHE BOOL "" FORCE)
set(NO_WEBSOCKET OFF CACHE BOOL "" FORCE)
set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(MBEDTLS_FATAL_WARNINGS OFF CACHE BOOL "" FORCE)
set(DISABLE_PACKAGE_CONFIG_AND_INSTALL OFF CACHE BOOL "" FORCE)
set(MBEDTLS_USER_CONFIG_FILE "${CMAKE_CURRENT_BINARY_DIR}/ceres-tls/ceres_mbedtls_config.h" CACHE FILEPATH "" FORCE)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/ceres-tls")
file(CONFIGURE OUTPUT "${MBEDTLS_USER_CONFIG_FILE}" CONTENT "#pragma once\n#define MBEDTLS_SSL_DTLS_SRTP\n#define MBEDTLS_THREADING_C\n#ifdef _WIN32\n#define MBEDTLS_THREADING_ALT\n#else\n#define MBEDTLS_THREADING_PTHREAD\n#endif\n")
file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/ceres-tls/threading_alt.h" CONTENT "#pragma once\n#ifndef NOMINMAX\n#define NOMINMAX\n#endif\n#ifndef WIN32_LEAN_AND_MEAN\n#define WIN32_LEAN_AND_MEAN\n#endif\n#include <windows.h>\ntypedef struct { SRWLOCK lock; int valid; } mbedtls_threading_mutex_t;\n")
if(NOT WIN32)
  set(LINK_WITH_PTHREAD ON CACHE BOOL "" FORCE)
endif()
FetchContent_Declare(mbedtls GIT_REPOSITORY https://github.com/Mbed-TLS/mbedtls.git GIT_TAG e185d7fd85499c8ce5ca2a54f5cf8fe7dbe3f8df GIT_SUBMODULES framework GIT_SUBMODULES_RECURSE TRUE)
FetchContent_MakeAvailable(mbedtls)
target_include_directories(mbedcrypto PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/ceres-tls>")
# Supply the aggregate target used by libdatachannel and the variables used by libsrtp.
add_library(MbedTLS::MbedTLS INTERFACE IMPORTED GLOBAL)
set_target_properties(MbedTLS::MbedTLS PROPERTIES INTERFACE_LINK_LIBRARIES "mbedtls;mbedx509;mbedcrypto" INTERFACE_INCLUDE_DIRECTORIES "${mbedtls_SOURCE_DIR}/include")
set(MBEDTLS_INCLUDE_DIRS "${mbedtls_SOURCE_DIR}/include")
set(MBEDTLS_LIBRARY mbedtls)
set(MBEDX509_LIBRARY mbedx509)
set(MBEDCRYPTO_LIBRARY mbedcrypto)
set(MBEDTLS_LIBRARIES mbedtls mbedx509 mbedcrypto)
set(MbedTLS_INCLUDE_DIR "${mbedtls_SOURCE_DIR}/include")
set(MbedTLS_LIBRARY mbedtls)
set(MbedX509_LIBRARY mbedx509)
set(MbedCrypto_LIBRARY mbedcrypto)
add_library(MbedTLS ALIAS mbedtls)
add_library(MbedX509 ALIAS mbedx509)
add_library(MbedCrypto ALIAS mbedcrypto)
add_library(MbedTLS::MbedCrypto ALIAS mbedcrypto)
add_library(MbedTLS::MbedX509 ALIAS mbedx509)
set(ENABLE_WARNINGS_AS_ERRORS OFF CACHE BOOL "" FORCE)
set(LIBSRTP_TEST_APPS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(libdatachannel GIT_REPOSITORY https://github.com/paullouisageneau/libdatachannel.git GIT_TAG 8c31097ea78f051e857d0aa1b2f6efb26cd12b7e GIT_SUBMODULES deps/plog deps/usrsctp deps/libjuice deps/libsrtp GIT_SUBMODULES_RECURSE TRUE)
FetchContent_MakeAvailable(libdatachannel)
include("${CMAKE_CURRENT_LIST_DIR}/LibDataChannelTls.cmake")
# The upstream find module replaces aggregate link properties while configuring libsrtp.
set_target_properties(MbedTLS::MbedTLS PROPERTIES INTERFACE_LINK_LIBRARIES "mbedtls;mbedx509;mbedcrypto")
target_link_libraries(datachannel-static PUBLIC MbedTLS::MbedTLS)
find_package(Git REQUIRED)
foreach(dependency mbedtls libdatachannel)
  execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD WORKING_DIRECTORY "${${dependency}_SOURCE_DIR}" OUTPUT_VARIABLE dependency_revision OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  if(dependency STREQUAL "mbedtls")
    set(expected_revision e185d7fd85499c8ce5ca2a54f5cf8fe7dbe3f8df)
  else()
    set(expected_revision 8c31097ea78f051e857d0aa1b2f6efb26cd12b7e)
  endif()
  if(NOT dependency_revision STREQUAL expected_revision)
    message(FATAL_ERROR "${dependency} revision differs from the pinned source")
  endif()
endforeach()
