include_guard(GLOBAL)
set(CERES_GRAPHICS_BACKEND AUTO CACHE STRING "Graphics/compute backend: AUTO, OPENGL_CUDA or METAL")
set_property(CACHE CERES_GRAPHICS_BACKEND PROPERTY STRINGS AUTO OPENGL_CUDA METAL)
string(TOUPPER "${CERES_GRAPHICS_BACKEND}" ceres_graphics_backend)
if(ceres_graphics_backend STREQUAL "AUTO")
  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(ceres_graphics_backend METAL)
  else()
    set(ceres_graphics_backend OPENGL_CUDA)
  endif()
endif()
if(NOT ceres_graphics_backend MATCHES "^(OPENGL_CUDA|METAL)$")
  message(FATAL_ERROR "CERES_GRAPHICS_BACKEND must be AUTO, OPENGL_CUDA or METAL")
endif()
if(ceres_graphics_backend STREQUAL "METAL")
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin" OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64|ARM64)$")
    message(FATAL_ERROR "The Metal backend requires Apple Silicon macOS")
  endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  message(FATAL_ERROR "macOS requires the METAL graphics backend")
endif()
set(CERES_SELECTED_GRAPHICS_BACKEND "${ceres_graphics_backend}" CACHE INTERNAL "Graphics backend" FORCE)
message(STATUS "Graphics backend: ${CERES_SELECTED_GRAPHICS_BACKEND}")
