set(CERES_VIDEO_BACKEND AUTO CACHE STRING "Video decoder: AUTO, CUVID or JETSON")
set_property(CACHE CERES_VIDEO_BACKEND PROPERTY STRINGS AUTO CUVID JETSON)
set(CERES_JETSON_API_ROOT /usr/src/jetson_multimedia_api CACHE PATH "JetPack Multimedia API source")
string(TOUPPER "${CERES_VIDEO_BACKEND}" ceres_video_backend)
if(ceres_video_backend STREQUAL "AUTO")
  set(ceres_video_backend CUVID)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$"
     AND NOT CMAKE_CROSSCOMPILING AND EXISTS /etc/nv_tegra_release)
    file(READ /etc/nv_tegra_release ceres_l4t_release)
    # R36 is the JetPack 6/Orin stack. Thor's newer stack uses CUVID.
    if(ceres_l4t_release MATCHES "^# R36 ")
      set(ceres_video_backend JETSON)
    endif()
  endif()
endif()
if(NOT ceres_video_backend MATCHES "^(CUVID|JETSON)$")
  message(FATAL_ERROR "CERES_VIDEO_BACKEND must be AUTO, CUVID or JETSON")
endif()
if(ceres_video_backend STREQUAL "JETSON" AND
   (NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$"))
  message(FATAL_ERROR "The Jetson backend requires Linux ARM64 with JetPack 6")
endif()
set(CERES_SELECTED_VIDEO_BACKEND "${ceres_video_backend}" CACHE INTERNAL "Packaged video backend" FORCE)
message(STATUS "Video decoder: ${CERES_SELECTED_VIDEO_BACKEND}")

function(ceres_add_video_library)
  add_library(ceres_video STATIC src/nvdec.cpp)
  target_link_libraries(ceres_video PUBLIC ceres_core CUDA::cuda_driver)
  target_compile_definitions(ceres_video PRIVATE NOMINMAX)
  if(CERES_SELECTED_VIDEO_BACKEND STREQUAL "JETSON")
    if(NOT EXISTS "${CERES_JETSON_API_ROOT}/include/NvVideoDecoder.h")
      message(FATAL_ERROR "Install nvidia-l4t-jetson-multimedia-api from your JetPack repository, or set CERES_JETSON_API_ROOT")
    endif()
    find_library(CERES_NVBUFSURFACE_LIBRARY nvbufsurface
      PATHS /usr/lib/aarch64-linux-gnu/nvidia /usr/lib/aarch64-linux-gnu/tegra REQUIRED)
    find_library(CERES_V4L2_LIBRARY NAMES nvv4l2 libv4l2.so.0
      PATHS /usr/lib/aarch64-linux-gnu/nvidia /usr/lib/aarch64-linux-gnu/tegra
      NO_DEFAULT_PATH REQUIRED)
    find_path(CERES_EGL_INCLUDE_DIR EGL/egl.h REQUIRED)
    target_sources(ceres_video PRIVATE src/nvdec_jetson.cpp)
    foreach(source NvVideoDecoder NvV4l2Element NvV4l2ElementPlane NvBuffer NvElement NvElementProfiler NvLogging)
      target_sources(ceres_video PRIVATE "${CERES_JETSON_API_ROOT}/samples/common/classes/${source}.cpp")
    endforeach()
    target_include_directories(ceres_video SYSTEM PRIVATE
      "${CERES_JETSON_API_ROOT}/include" "${CERES_EGL_INCLUDE_DIR}")
    target_link_libraries(ceres_video PRIVATE "${CERES_NVBUFSURFACE_LIBRARY}" "${CERES_V4L2_LIBRARY}")
  else()
    target_sources(ceres_video PRIVATE src/nvdec_cuvid.cpp)
    target_include_directories(ceres_video PRIVATE "${nvcodec_SOURCE_DIR}/include/ffnvcodec")
    target_link_libraries(ceres_video PRIVATE ${CMAKE_DL_LIBS})
  endif()
endfunction()
