cmake_minimum_required(VERSION 3.25)
get_filename_component(viewer_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
foreach(required VIEWER_BUILD_DIR PACKAGE_DIR FFMPEG_ROOT)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "${required} must be supplied")
  endif()
  get_filename_component(${required} "${${required}}" ABSOLUTE)
endforeach()
if(NOT DEFINED BUILD_CONFIG)
  set(BUILD_CONFIG Release)
endif()
if(EXISTS "${PACKAGE_DIR}")
  message(FATAL_ERROR "Package directory already exists: ${PACKAGE_DIR}")
endif()
if(NOT EXISTS "${VIEWER_BUILD_DIR}/CMakeCache.txt")
  message(FATAL_ERROR "Viewer build directory has no CMake configuration")
endif()

function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result COMMAND_ECHO STDOUT)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Package command failed with status ${result}")
  endif()
endfunction()
function(cache_value key output)
  file(STRINGS "${VIEWER_BUILD_DIR}/CMakeCache.txt" lines REGEX "^${key}:[^=]*=")
  if(lines)
    list(GET lines 0 line)
    string(REGEX REPLACE "^[^=]*=" "" value "${line}")
    set(${output} "${value}" PARENT_SCOPE)
  else()
    set(${output} "" PARENT_SCOPE)
  endif()
endfunction()
function(copy_notice_file source destination)
  file(MAKE_DIRECTORY "${destination}")
  get_filename_component(name "${source}" NAME)
  file(COPY_FILE "${source}" "${destination}/${name}" ONLY_IF_DIFFERENT)
endfunction()
function(copy_notice_tree source destination)
  file(GLOB_RECURSE notices LIST_DIRECTORIES FALSE FOLLOW_SYMLINKS RELATIVE "${source}" "${source}/*")
  foreach(notice IN LISTS notices)
    get_filename_component(parent "${notice}" DIRECTORY)
    copy_notice_file("${source}/${notice}" "${destination}/${parent}")
  endforeach()
endfunction()
function(copy_licences label directory)
  file(GLOB files LIST_DIRECTORIES FALSE
    "${directory}/LICENSE*" "${directory}/LICENCE*" "${directory}/COPYING*"
    "${directory}/NOTICE*" "${directory}/copying*" "${directory}/Copyright*"
    "${directory}/copyright*" "${directory}/license*" "${directory}/licence*"
    "${directory}/License*" "${directory}/Licence*" "${directory}/Notice*" "${directory}/COPYRIGHT*")
  if(files)
    foreach(path IN LISTS files)
      copy_notice_file("${path}" "${PACKAGE_DIR}/licences/${label}")
    endforeach()
  endif()
  foreach(folder LICENSES licenses)
    if(IS_DIRECTORY "${directory}/${folder}")
      copy_notice_tree("${directory}/${folder}" "${PACKAGE_DIR}/licences/${label}/${folder}")
    endif()
  endforeach()
endfunction()

get_filename_component(source_root "${viewer_root}/../.." ABSOLUTE)
set(EXPORTER_SOURCE "${source_root}")
set(exporter_crate "${source_root}/native/lerobot-exporter")
set(exporter_manifest "${exporter_crate}/Cargo.toml")
set(exporter_binary ceres-native-exporter)
set(exporter_target "${VIEWER_BUILD_DIR}/_package/exporter-target")
if(NOT EXISTS "${exporter_manifest}")
  message(FATAL_ERROR "The sibling native/lerobot-exporter source is required")
endif()
find_program(CARGO_EXECUTABLE cargo REQUIRED)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
execute_process(COMMAND "${CARGO_EXECUTABLE}" build --locked --release --manifest-path "${exporter_manifest}"
  --target-dir "${exporter_target}" --bin "${exporter_binary}"
  WORKING_DIRECTORY "${EXPORTER_SOURCE}" RESULT_VARIABLE result COMMAND_ECHO STDOUT)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Sibling exporter build failed")
endif()

if(CMAKE_HOST_WIN32)
  set(exe .exe)
else()
  set(exe "")
endif()
file(MAKE_DIRECTORY "${PACKAGE_DIR}")
run("${CMAKE_COMMAND}" --install "${VIEWER_BUILD_DIR}" --config "${BUILD_CONFIG}" --component ViewerRuntime --prefix "${PACKAGE_DIR}")
file(COPY "${exporter_target}/release/${exporter_binary}${exe}" DESTINATION "${PACKAGE_DIR}")
foreach(binary ffmpeg ffprobe)
  if(EXISTS "${FFMPEG_ROOT}/bin/${binary}${exe}")
    set(ffmpeg_bin "${FFMPEG_ROOT}/bin")
  elseif(EXISTS "${FFMPEG_ROOT}/${binary}${exe}")
    set(ffmpeg_bin "${FFMPEG_ROOT}")
  else()
    message(FATAL_ERROR "${binary}${exe} is missing from FFMPEG_ROOT")
  endif()
  file(COPY "${ffmpeg_bin}/${binary}${exe}" DESTINATION "${PACKAGE_DIR}")
endforeach()
file(MAKE_DIRECTORY "${PACKAGE_DIR}/licences" "${PACKAGE_DIR}/provenance")
file(COPY "${viewer_root}/cmake/Dependencies.cmake" "${viewer_root}/CMakeLists.txt" DESTINATION "${PACKAGE_DIR}/provenance")
file(COPY "${exporter_crate}/Cargo.lock" DESTINATION "${PACKAGE_DIR}/provenance")
file(COPY "${source_root}/package.json" DESTINATION "${PACKAGE_DIR}/provenance")
foreach(receipt ffmpeg-source-lock.json ffmpeg-receipt.json)
  if(EXISTS "${FFMPEG_ROOT}/${receipt}")
    file(COPY "${FFMPEG_ROOT}/${receipt}" DESTINATION "${PACKAGE_DIR}/provenance")
  endif()
endforeach()
copy_licences(ceres-viewer "${viewer_root}")
copy_licences(ceres-exporter "${EXPORTER_SOURCE}")
copy_licences(ffmpeg "${FFMPEG_ROOT}")
foreach(notice README.txt README.md)
  if(EXISTS "${FFMPEG_ROOT}/${notice}")
    file(COPY "${FFMPEG_ROOT}/${notice}" DESTINATION "${PACKAGE_DIR}/licences/ffmpeg")
  endif()
endforeach()
if(EXISTS "${FFMPEG_ROOT}/doc")
  file(COPY "${FFMPEG_ROOT}/doc" DESTINATION "${PACKAGE_DIR}/licences/ffmpeg")
endif()
if(FFMPEG_LICENCES)
  copy_notice_tree("${FFMPEG_LICENCES}" "${PACKAGE_DIR}/licences/ffmpeg")
endif()
file(GLOB ffmpeg_notices "${PACKAGE_DIR}/licences/ffmpeg/*")
if(NOT ffmpeg_notices)
  message(FATAL_ERROR "The FFmpeg distribution must include its licence and source notices")
endif()

foreach(dependency json mcap glfw glm glad imgui qrcode nvcodec curl libdatachannel mbedtls)
  string(TOUPPER "${dependency}" upper)
  cache_value("FETCHCONTENT_SOURCE_DIR_${upper}" source)
  if(NOT source)
    set(source "${VIEWER_BUILD_DIR}/_deps/${dependency}-src")
  endif()
  copy_licences("${dependency}" "${source}")
  if(dependency STREQUAL "qrcode")
    file(COPY "${source}/cpp/qrcodegen.hpp" DESTINATION "${PACKAGE_DIR}/licences/qrcode")
  elseif(dependency STREQUAL "nvcodec")
    file(COPY "${source}/include/ffnvcodec/dynlink_nvcuvid.h" DESTINATION "${PACKAGE_DIR}/licences/nvcodec")
  elseif(dependency STREQUAL "libdatachannel")
    foreach(child libjuice libsrtp plog usrsctp)
      copy_licences("${child}" "${source}/deps/${child}")
    endforeach()
  endif()
endforeach()

execute_process(COMMAND "${CARGO_EXECUTABLE}" metadata --locked --format-version 1 --manifest-path "${exporter_manifest}"
  WORKING_DIRECTORY "${EXPORTER_SOURCE}" OUTPUT_VARIABLE cargo_metadata RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Could not collect exporter dependency licences")
endif()
string(JSON package_count LENGTH "${cargo_metadata}" packages)
math(EXPR last_package "${package_count} - 1")
set(rust_notices "")
foreach(index RANGE 0 ${last_package})
  string(JSON package_name GET "${cargo_metadata}" packages ${index} name)
  string(JSON package_version GET "${cargo_metadata}" packages ${index} version)
  string(JSON package_manifest GET "${cargo_metadata}" packages ${index} manifest_path)
  string(JSON package_licence GET "${cargo_metadata}" packages ${index} license)
  get_filename_component(package_source "${package_manifest}" DIRECTORY)
  copy_licences("rust/${package_name}-${package_version}" "${package_source}")
  string(JSON licence_file GET "${cargo_metadata}" packages ${index} license_file)
  if(licence_file)
    if(NOT IS_ABSOLUTE "${licence_file}")
      set(licence_file "${package_source}/${licence_file}")
    endif()
    copy_notice_file("${licence_file}" "${PACKAGE_DIR}/licences/rust/${package_name}-${package_version}")
  endif()
  string(APPEND rust_notices "${package_name} ${package_version}: ${package_licence}\n")
endforeach()
file(WRITE "${PACKAGE_DIR}/licences/rust-dependencies.txt" "${rust_notices}")

if(NOT CUDA_ROOT)
  cache_value(CMAKE_CUDA_COMPILER cuda_compiler)
  get_filename_component(cuda_bin "${cuda_compiler}" DIRECTORY)
  get_filename_component(CUDA_ROOT "${cuda_bin}" DIRECTORY)
endif()
copy_licences(nvidia-cuda "${CUDA_ROOT}")
if(EXISTS "${CUDA_ROOT}/EULA.txt")
  file(COPY "${CUDA_ROOT}/EULA.txt" DESTINATION "${PACKAGE_DIR}/licences/nvidia-cuda")
endif()
set(runtime_dirs "${PACKAGE_DIR}" "${ffmpeg_bin}" "${CUDA_ROOT}/bin" "${CUDA_ROOT}/lib64")
file(GLOB_RECURSE build_dlls LIST_DIRECTORIES FALSE "${VIEWER_BUILD_DIR}/*.dll")
foreach(library IN LISTS build_dlls)
  get_filename_component(directory "${library}" DIRECTORY)
  list(APPEND runtime_dirs "${directory}")
endforeach()
list(REMOVE_DUPLICATES runtime_dirs)
set(executables "${PACKAGE_DIR}/ceres-viewer${exe}" "${PACKAGE_DIR}/${exporter_binary}${exe}"
  "${PACKAGE_DIR}/ffmpeg${exe}" "${PACKAGE_DIR}/ffprobe${exe}")

if(CMAKE_HOST_WIN32)
  if(NOT MSVC_REDIST_DIR OR NOT EXISTS "${MSVC_REDIST_DIR}")
    message(FATAL_ERROR "MSVC_REDIST_DIR must identify the app-local x64 Microsoft CRT")
  endif()
  file(GLOB crt_dlls "${MSVC_REDIST_DIR}/*.dll")
  if(NOT crt_dlls)
    message(FATAL_ERROR "Microsoft CRT DLLs are missing")
  endif()
  file(COPY ${crt_dlls} DESTINATION "${PACKAGE_DIR}")
  if(MSVC_LICENCES)
    file(COPY "${MSVC_LICENCES}/" DESTINATION "${PACKAGE_DIR}/licences/microsoft-runtime")
  endif()
  if(DUMPBIN_EXECUTABLE)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM windows+pe)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL dumpbin)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${DUMPBIN_EXECUTABLE}")
  endif()
  file(GET_RUNTIME_DEPENDENCIES EXECUTABLES ${executables}
    DIRECTORIES ${runtime_dirs} RESOLVED_DEPENDENCIES_VAR resolved UNRESOLVED_DEPENDENCIES_VAR unresolved
    PRE_EXCLUDE_REGEXES "^[Aa][Pp][Ii]-[Mm][Ss]-" "^[Ee][Xx][Tt]-[Mm][Ss]-" "^[Nn][Vv][Cc][Uu][Dd][Aa]\\.dll$" "^[Nn][Vv][Cc][Uu][Vv][Ii][Dd]\\.dll$"
    POST_EXCLUDE_REGEXES ".*[\\\\/][Ww][Ii][Nn][Dd][Oo][Ww][Ss][\\\\/].*")
  set(runtime_destination "${PACKAGE_DIR}")
else()
  file(GET_RUNTIME_DEPENDENCIES EXECUTABLES ${executables}
    DIRECTORIES ${runtime_dirs} RESOLVED_DEPENDENCIES_VAR resolved UNRESOLVED_DEPENDENCIES_VAR unresolved
    PRE_EXCLUDE_REGEXES "^lib(cuda|nvcuvid|nvidia.*|GL|GLX.*|OpenGL|EGL|GLdispatch)\\.so"
      "^ld-linux.*" "^lib(c|m|dl|pthread|rt|resolv|util)\\.so")
  set(runtime_destination "${PACKAGE_DIR}/lib")
endif()
if(unresolved)
  message(FATAL_ERROR "Unresolved package runtime dependencies: ${unresolved}")
endif()
file(MAKE_DIRECTORY "${runtime_destination}")
foreach(library IN LISTS resolved)
  file(COPY "${library}" DESTINATION "${runtime_destination}" FOLLOW_SYMLINK_CHAIN)
  if(NOT CMAKE_HOST_WIN32 AND EXISTS /usr/bin/dpkg-query)
    execute_process(COMMAND /usr/bin/dpkg-query -S "${library}" OUTPUT_VARIABLE owner ERROR_QUIET)
    string(REGEX MATCH "^[^:]+" package "${owner}")
    if(package AND EXISTS "/usr/share/doc/${package}/copyright")
      copy_notice_file("/usr/share/doc/${package}/copyright" "${PACKAGE_DIR}/licences/system/${package}")
    endif()
  endif()
endforeach()
if(NOT CMAKE_HOST_WIN32)
  file(RENAME "${PACKAGE_DIR}/ceres-viewer" "${PACKAGE_DIR}/ceres-viewer.bin")
  file(WRITE "${PACKAGE_DIR}/ceres-viewer" "#!/bin/sh\napp_dir=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\nexport LD_LIBRARY_PATH=\"$app_dir/lib\${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"\nexec \"$app_dir/ceres-viewer.bin\" \"$@\"\n")
  file(CHMOD "${PACKAGE_DIR}/ceres-viewer" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
  set(ENV{LD_LIBRARY_PATH} "${PACKAGE_DIR}/lib")
endif()

execute_process(COMMAND "${PACKAGE_DIR}/${exporter_binary}${exe}" --capabilities
  OUTPUT_VARIABLE exporter_capabilities RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Packaged exporter could not start")
endif()
string(JSON capability_schema GET "${exporter_capabilities}" schema)
string(JSON capability_profile GET "${exporter_capabilities}" default_profile)
string(JSON capability_lerobot GET "${exporter_capabilities}" lerobot)
string(JSON capability_actions GET "${exporter_capabilities}" action_dimension)
string(JSON capability_shards GET "${exporter_capabilities}" ceres_episode_shards)
string(JSON capability_job_version GET "${exporter_capabilities}" job_version)
string(JSON capability_has_actions GET "${exporter_capabilities}" actions)
string(JSON capability_source_dimensions GET "${exporter_capabilities}" source_video_dimensions)
string(JSON capability_profile_count LENGTH "${exporter_capabilities}" profiles)
set(capability_supports_profile FALSE)
if(capability_profile_count GREATER 0)
  math(EXPR capability_last_profile "${capability_profile_count} - 1")
  foreach(index RANGE 0 ${capability_last_profile})
    string(JSON capability_supported_profile GET "${exporter_capabilities}" profiles ${index})
    if(capability_supported_profile STREQUAL "ceres-bridge-lerobot3-v1")
      set(capability_supports_profile TRUE)
    endif()
  endforeach()
endif()
if(NOT capability_schema STREQUAL "ceres-native-export-capabilities" OR
   NOT capability_profile STREQUAL "ceres-bridge-lerobot3-v1" OR
   NOT capability_lerobot STREQUAL "v3.0" OR
   NOT capability_actions EQUAL 2 OR NOT capability_shards OR
   NOT capability_job_version EQUAL 1 OR NOT capability_has_actions OR
   NOT capability_supports_profile OR NOT capability_source_dimensions)
  message(FATAL_ERROR "Packaged exporter capabilities differ")
endif()
file(WRITE "${PACKAGE_DIR}/provenance/exporter-capabilities.json" "${exporter_capabilities}")
execute_process(COMMAND "${PACKAGE_DIR}/ffmpeg${exe}" -version OUTPUT_VARIABLE ffmpeg_version RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Packaged FFmpeg could not start")
endif()
execute_process(COMMAND "${PACKAGE_DIR}/ffmpeg${exe}" -hide_banner -encoders OUTPUT_VARIABLE encoders RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT encoders MATCHES "libx264")
  message(FATAL_ERROR "Packaged FFmpeg must provide the libx264 encoder")
endif()
run("${PACKAGE_DIR}/ffprobe${exe}" -version)
file(WRITE "${PACKAGE_DIR}/provenance/ffmpeg-version.txt" "${ffmpeg_version}")
cache_value(CMAKE_CUDA_ARCHITECTURES cuda_architectures)
string(REPLACE ";" "," cuda_architectures_argument "${cuda_architectures}")
run("${Python3_EXECUTABLE}" "${viewer_root}/scripts/package-common.py"
  --package "${PACKAGE_DIR}" --source "${source_root}" --platform "${PACKAGE_PLATFORM}"
  --build "${VIEWER_BUILD_DIR}" --cuda-architectures "${cuda_architectures_argument}")
message(STATUS "Package ready: ${PACKAGE_DIR}")
